"""Add OTP fields to User model

Revision ID: 25e25d6600de
Revises: 08fb16125655
Create Date: 2025-03-30 12:50:16.914970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e25d6600de'
down_revision = '08fb16125655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('otp_created_at')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
