"""Add PitchRegistration model with plural backrefs

Revision ID: 585bdee24366
Revises: be3c6f9f85ae
Create Date: 2025-04-04 17:31:02.888050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '585bdee24366'
down_revision = 'be3c6f9f85ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitching_registration')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('pitching_registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pitch_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pitch_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('problem_statement', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('solution_approach', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('market_analysis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business_model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_background', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pitch_deck_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('additional_docs_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('video_pitch_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='pitching_registration_event_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='pitching_registration_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pitching_registration_pkey')
    )
    # ### end Alembic commands ###
