"""Add subtitle field to Event model

Revision ID: 959ac909df4d
Revises: 25e25d6600de
Create Date: 2025-04-04 14:28:19.281266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '959ac909df4d'
down_revision = '25e25d6600de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch_registration')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    op.create_table('pitch_registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('business_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_market', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('funding_needed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_traction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pitch_deck_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('competitive_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_background', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('linkedin_profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='pitch_registration_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pitch_registration_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pitch_registration_pkey')
    )
    # ### end Alembic commands ###
