"""Fix relationships between Event and PitchingRegistration

Revision ID: be3c6f9f85ae
Revises: 0d4902ca4a39
Create Date: 2025-04-04 17:02:35.856904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3c6f9f85ae'
down_revision = '0d4902ca4a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pitching_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.alter_column('pitch_title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitching_registration', schema=None) as batch_op:
        batch_op.alter_column('pitch_title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
